SPECS = {
 'safari-url-pill': dict(file='Web/Crops/ios-safari-bottom-bar-native--url-pill-left-end.png', box=(19, 17.5, 1000, 161.5), r=72,
                         corners=['TL', 'BL'], free=[0, 1, 3], pol='fall', win=3, win0=6, reach=150),
 'mac-cc-music-tile': dict(file='Apple/Crops/newsroom-macos26-control-center-mac-cc-music-tile.png', box=(11, 15, 565, 569), r=90,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=3, win0=6),
 'mac-cc-album-art': dict(file='Apple/Crops/newsroom-macos26-control-center-mac-cc-music-tile.png', box=(67, 71.5, 233, 237.5), r=38,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='abs', win=2.5, win0=5),
 'ipad-clock-widget': dict(file='Apple/Crops/newsroom-ipados26-home-screen-ipad-widgets.png', box=(13.5, 30, 333, 349), r=70,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=3, win0=6),
 'ipad-weather-widget': dict(file='Apple/Crops/newsroom-ipados26-home-screen-ipad-widgets.png', box=(20, 416.5, 2000, 733), r=70,
                         corners=['TL', 'BL'], free=[0, 1, 3], pol='fall', win=3, win0=6),
 'ios-notification-card': dict(file='Web/Crops/ios-notification-center-and-music--notification-cards.png', box=(21.5, 47, 2000, 183.5), r=45,
                         corners=['TL', 'BL'], free=[0, 1, 3], pol='fall', win=2.5, win0=4),
 'ios-context-menu': dict(file='Web/Crops/ios-18-vs-26-photos-context-menu--context-menu-corner.png', box=(11.5, 18.5, 426.5, 2000), r=55,
                         corners=['TL', 'TR'], free=[0, 1, 2], pol='abs', win=2.5, win0=4),
 'ios-safari-tab-menu': dict(file='Web/Crops/ios-safari-bar-and-menu--tab-menu-corner-over-blue.png', box=(24.5, 26, 554.5, 2000), r=60,
                         corners=['TL', 'TR'], free=[0, 1, 2], pol='fall', win=2.5, win0=4),
 'mac-control-tile': dict(file='Web/Crops/macos-tahoe-desktop-control-center--control-tiles.png', box=(156, 12.5, 217, 69), r=15,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=2, win0=3),
 'ios-answer-card': dict(file='Web/Crops/ios-screenshot-editor-glass-toolbar--answer-card-corner.png', box=(10, 20.5, 2000, 2000), r=45,
                         corners=['TL'], free=[0, 1], pol='fall', win=2.5, win0=4),
 'mac-weather-widget': dict(file='Web/Crops/macos-tahoe-menu-and-widgets-over-mountains--weather-widget-over-sky.png', box=(-2000, 18, 317, 296), r=40,
                         corners=['TR', 'BR'], free=[1, 2, 3], pol='rise', win=2.5, win0=4),
 'ios-findmy-widget': dict(file='Apple/Crops/newsroom-ios26-home-screen-customization-clear-widgets.png', box=(405.5, 34, 745, 373), r=60,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=2.5, win0=4),
 'ios-app-icon': dict(file='Apple/Crops/newsroom-ios26-home-screen-customization-clear-icons.png', box=(32.5, 26.5, 165.5, 159.5), r=30,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=2.5, win0=4),
 'mac-cc-circle': dict(file='Apple/Crops/newsroom-macos26-control-center-mac-cc-wifi-bluetooth.png', box=(10.5, 316, 264, 569.5), r=127,
                         corners=['TL', 'TR', 'BL', 'BR'], free=[0, 1, 2, 3], pol='fall', win=2.5, win0=4),
 'mac-cc-wifi-pill': dict(file='Apple/Crops/newsroom-macos26-control-center-mac-cc-wifi-bluetooth.png', box=(10, 15.5, 2000, 268.5), r=126,
                         corners=['TL', 'BL'], free=[0, 1, 3], pol='fall', win=2.5, win0=4, reach=260),
}
